<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
		<Authors>Delly.Net</Authors>
		<Version>1.0.2609.1</Version>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>ref_256.png</PackageIcon>
		<RepositoryUrl>https://github.com/delly-net/Refer</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
	  <None Update="README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Update="ref_256.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
